# Generated by Django 3.1.1 on 2020-09-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='order_address',
            field=models.CharField(max_length=100),
        ),
    ]
